### ISSUE TITLE
dockerhub sample uses the wrong port

### ISSUE THREAD

**Issue by Trolldemorted** [TheHive-Project/Cortex#203]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | -
| OS version (client)       | -
| Cortex version / git hash   | -
| Package Type              | Docker
| Browser type & version    | -

### Problem Description
This is the sample docker-compose file on [dockerhub](https://hub.docker.com/r/thehiveproject/thehive):
```
version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - script.inline=true
      - thread_pool.index.queue_size=100000
      - thread_pool.search.queue_size=100000
      - thread_pool.bulk.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  cortex:
    image: thehiveproject/cortex:latest
    ports:
      - "0.0.0.0:9001:9000"
  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
```

As you can see, it maps `- "0.0.0.0:9001:9000"` where `- "9001:9001"` would be correct. If this is the wrong repository please excuse me, but I couldn't find where your docker documentation lives.
