### ISSUE TITLE
"latest" dockerhub build tagged wrong

### ISSUE THREAD

**Issue by druesendieb** [TheHive-Project/Cortex#267]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04 LTS
| Cortex version / git hash   | Docker build 3.0.1 vs "latest"
| Package Type              | Docker

### Problem Description
The [latest](https://hub.docker.com/layers/thehiveproject/cortex/latest/images/sha256-42caa13f5139f0369c555f3374051be6644336c4d840a9b5fa9ae8ad2216fd50?context=explore) tagged image on Dockerhub is a build from 2018 (org.label-schema.build-date=2018-12-20T13:58:32Z). When deploying TheHive and Cortex according to the [TheHive Installguide](https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#docker) the deployment fails because the dockerbuild from 2018 doesnt support Elastic Search 6.8.8 as used in the installguide.

### Steps to Reproduce
1. Use the [TheHive Installguide docker-compose](https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#docker) file to deploy containers
```
version: "2"
services:
  elasticsearch:
    image: elasticsearch:6.8.8
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    command: --cortex-port 9001
```
2. After the deployment of the containers, go to the cortex webinterface and start the migration 

3. See it failing:
```
cortex_1         | [error] o.e.s.MigrationSrv - Migration fail 
cortex_1         | org.elasticsearch.transport.RemoteTransportException: [wtjB3qz][10.10.1.2:9300][indices:admin/create] 
cortex_1         | Caused by: org.elasticsearch.index.mapper.MapperParsingException:Failed to parse mapping [artifact]: [_parent] field is disabled on indices with a single type. Use a [join] field instead.
cortex_1         |      at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:399)
cortex_1         |      at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:330)
cortex_1         |      at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:481)
cortex_1         |      at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
cortex_1         |      at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
cortex_1         |      at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270)
cortex_1         |      at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:200)
cortex_1         |      at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:135) 
cortex_1         |      at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
cortex_1         |      at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
```

### Possible Solutions
Tag [cortex:3.0.1](https://hub.docker.com/layers/thehiveproject/cortex/3.0.1/images/sha256-ed1de827eb05687b730d2420b14e8e6e941e7f6d4a15051b4ab6ab2baf00380f?context=explore)  as latest.
Deployment with "image: thehiveproject/cortex:3.0.1" instead of "image: thehiveproject/cortex:latest" works like a charm!
