### ISSUE TITLE
Cortex failed to migrate database after a fresh install through docker-compose

### ISSUE THREAD

**Issue by senyuuri** [TheHive-Project/Cortex#277]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | OS X 10.15.4
| OS version (client)       | OS X 10.15.4
| Cortex version / git hash   | 2.1.3
| Package Type              | Docker
| Browser type & version    | Chrome/83.0.4103.116 

### Problem Description
Cortex cannot update the database after a fresh install by using the official docker-compose file
(https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#docker)

### Steps to Reproduce
1. Download the attached docker-compose.yml and 'docker-compose up'
2. Goto `localhost:9001` and click on "Update database"
3. An error message of "UserMgmtCtrl" pops up

### Complementary information
**Screenshots**
![image](https://user-images.githubusercontent.com/2610986/87403113-08941700-c5ef-11ea-9274-f9de6fd68b52.png)

**Logs**
```
cortex_1         | [info] o.e.s.MigrationSrv - Create a new empty database
cortex_1         | [info] o.e.s.MigrationSrv - Migrate database from version 0, add operations for version 2
cortex_1         | [error] o.e.s.MigrationSrv - Migration fail
cortex_1         | org.elasticsearch.transport.RemoteTransportException: [WwWB9-K][172.21.0.2:9300][indices:admin/create]
cortex_1         | Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [artifact]: [_parent] field is disabled on indices with a single type. Use a [join] field instead.
cortex_1         | 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:399)
cortex_1         | 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:330)
cortex_1         | 	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:481)
cortex_1         | 	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
cortex_1         | 	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
cortex_1         | 	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270)
cortex_1         | 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:200)
cortex_1         | 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:135)
cortex_1         | 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
cortex_1         | 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
cortex_1         | Caused by: org.elasticsearch.index.mapper.MapperParsingException: [_parent] field is disabled on indices with a single type. Use a [join] field instead.
cortex_1         | 	at org.elasticsearch.index.mapper.ParentFieldMapper$Builder.build(ParentFieldMapper.java:101)
cortex_1         | 	at org.elasticsearch.index.mapper.ParentFieldMapper$Builder.build(ParentFieldMapper.java:74)
cortex_1         | 	at org.elasticsearch.index.mapper.DocumentMapper$Builder.put(DocumentMapper.java:99)
cortex_1         | 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:127)
cortex_1         | 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92)
cortex_1         | 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:396)
cortex_1         | 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:330)
cortex_1         | 	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:481)
cortex_1         | 	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
cortex_1         | 	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
cortex_1         | [
```

**docker-compose.yml**
```
version: "3"
services:
  elasticsearch:
    image: elasticsearch:6.8.8
    environment:
      - http.host=0.0.0.0
      - cluster.name=hive
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data:/usr/share/elasticsearch/data
    
    
  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"

  thehive:
    image: thehiveproject/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    command: --cortex-port 9001

volumes:
    es-data:
```

**Comment by senyuuri** [comment]
Closing this issue as it's solved after upgrading to 3.0.1

**Comment by plonxyz** [comment]
hi @senyuuri , currently facing the same issue .. what exactly do you have updated? thx

**Comment by senyuuri** [comment]
Hi @plonxyz,

The true problem is, the 'latest' Cortex docker image was outdated. If you check the tag on DockerHub(https://hub.docker.com/r/thehiveproject/cortex/tags), the 'latest' image was uploaded 2 years ago which has the same hash as '2.1.3'. The newest one should be 3.0.1.

All I did was to update the image tag in the docker compose file:
```
cortex:
    image: thehiveproject/cortex:3.0.1
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
```

Hope this helps.
