### ISSUE TITLE
Cortex - Secured ElasticSearch Throws Invalid Certification Path

### ISSUE THREAD

**Issue by chberti** [TheHive-Project/Cortex#369]
# Configuring Cortex to join a secured ElasticSearch Cluster fails : Unable to find valid certification path

### Request Type
Question, Bug ?

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |  CentOS
| OS version (client)       | 10
| Cortex version / git hash   | 3.1.1
| Package Type              | Docker
| Browser type & version    | If applicable

### Problem Description
Hi there !
I am trying to configure a Cortex instance from the docker image.
As I already have a secured ElasticSearch Cluster, I want to use it in order to store Cortex' Data.
When the instance tries to connect to ES, it throws an error : `unable to find valid certification path to requested target`.
I checked the server name in my truststore.jks and it shows up, so I think my truststore is fine.

If I understand the concept well, I do not need a keystore for my instance if Cortex runs on HTTP only.  Anyway, I tried to configure both truststore and keystore  in the application.conf file and I get a different error : `UnrecoverableKeyException : Cannot recover key`

You will find my configuration files below

### Steps to Reproduce
1. Get a fine running ElasticSearch Cluster with HTTPS enabled
2. Configure a .jks truststore and import ES Cluster's CA and nodes certificates to it
3. Check the server is trusted using `keytool -v -list -keystore config/truststore.jks -alias 10.10.10.2`
3. Tel Cortex to run with this ES Cluster configured, use the truststore only.
4. At startup Cortex will tell you the certification path is wrong.

### Possible Solutions
I think I have some misunderstanding with keystore/truststore configuration (not very used to those). I already checked the following issue : https://github.com/TheHive-Project/Cortex/issues/358
My configuration is very similar but I get an error before the step Canon88 was.

Thank you by advance !

### Complementary information

**application.conf file**

```
# Sample Cortex application.conf file
## SECRET KEY
#
# The secret key is used to secure cryptographic functions.
#
# IMPORTANT: If you deploy your application to several  instances,  make
# sure to use the same key.
#play.http.secret.key="***CHANGEME***"
## ElasticSearch
search {
  # Name of the index
  index = cortex
  # ElasticSearch instance address.
  # For cluster, join address:port with ',': "http://ip1:9200,ip2:9200,ip3:9200"
  uri = "https://10.10.10.2:9200"
  ## Authentication configuration
  user = "elastic"
  password = "ch@ngeme!"
  ## SSL configuration
  keyStore {
    path = "/etc/cortex/truststore.jks"
    type = "JKS" # or PKCS12
    password = "ch@ngeme!"
  }
  trustStore {
    path = "/etc/cortex/truststore.jks"
    type = "JKS" # or PKCS12
    password = "ch@ngeme!"
  }
}
cache.job = 10 minutes
## Authentication
auth {
        provider = [local]
        ad {
        }
        ldap {
        }
    oauth2 {
    }
    # Single-Sign On
    sso {
    }
}
analyzer {
  # analyzer location
  # url can be point to:
  # - directory where analyzers are installed
  # - json file containing the list of analyzer descriptions
  urls = [
    "/data/cortex/analyzers/analyzers.json"
  ]
  # Sane defaults. Do not change unless you know what you are doing.
  fork-join-executor {
    # Min number of threads available for analysis.
    parallelism-min = 2
    # Parallelism (threads) ... ceil(available processors * factor).
    parallelism-factor = 2.0
    # Max number of threads available for analysis.
    parallelism-max = 4
  }
}
# RESPONDERS
#
responder {
  # responder location (same format as analyzer.urls)
  urls = [
  #  "https://download.thehive-project.org/responders.json"
    #"/absolute/path/of/responders"
  ]
  # Sane defaults. Do not change unless you know what you are doing.
  fork-join-executor {
    # Min number of threads available for analysis.
    parallelism-min = 2
    # Parallelism (threads) ... ceil(available processors * factor).
    parallelism-factor = 2.0
    # Max number of threads available for analysis.
    parallelism-max = 4
  }
}
```

**docker-compose.yml file***
```
version: 


services:
  cortex:
    image: thehiveproject/cortex:3.1.1
    environment:
      - job_directory=/data/cortex/tmp/cortex_jobs
      - docker_job_directory=/data/cortex/jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/cortex/jobs:/data/cortex/tmp/cortex_jobs
      - /data/cortex/analyzers:/data/cortex/analyzers
      - /data/cortex/config/application.conf:/etc/cortex/application.conf 
      - /data/cortex/config/truststore.jks:/etc/cortex/truststore.jks
    ports:
      - "0.0.0.0:9001:9001"
```
