### ISSUE TITLE
Cortex with Elasticsearch SSL

### ISSUE THREAD

**Issue by V1D1AN** [TheHive-Project/Cortex#373]
# Cortex with Elasticsearch SSL

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Cortex 3.1.1-1
| OS version (client)       | W10
| Package Type              | Docker,
| Browser type & version    | If applicable

### Problem Description
In the documentation, i follow the configuration of Elasticsearch with SSL X-PACK but it don't work for me.

Extract of application.conf for cortex:
```
  ## Authentication configuration
  user = "elastic"
  password = "password"
  ssl.enabled = true
  ssl.ca = "/opt/cortex/certificates/ca/ca.crt"
```

Extract of my docker-compose:
```
  cortex:
    image: 'cortex:3.1.1-1'
    container_name: cortex
    hostname: cortex
    restart: always
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf:ro
      - certs:/opt/cortex/certificates
    networks:
      - s1em
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cortex.rule=PathPrefix(`/cortex`)"
      - "traefik.http.routers.cortex.entryPoints=secure"
      - "traefik.http.routers.cortex.tls=true"
```

For working, I must do:
```
docker exec -ti cortex keytool -import -alias ca -file /opt/cortex/certificates/ca/ca.crt -keystore /usr/local/openjdk-8/jre/lib/security/cacerts
```

Question; 
What is the good configuration for configuring the CA certificate ?
